#!/bin/bash

notes_editor=vim
notes_prefix=Notes
notes_extension=org

command=$(basename $0)
if [[ "$NOTES_DIR" == "" ]]; then
	notes_dir=$HOME/Dropbox/Notes
else
	notes_dir="$NOTES_DIR"
fi

openFile() {
   if [ "$1" != "" ] ; then
	   file=${notes_prefix}_$1.org
   else
	   file=${notes_prefix}_$(date +%m-%d).org
   fi
   if [ ! -d "$notes_dir" ]; then
	   echo "Creating note directory $notes_dir"
	   echo -n "Press enter to continue"
	   read b
	   mkdir -p $notes_dir
   fi
   pushd $notes_dir
   $notes_editor $notes_dir/$file
   popd
}

findFile() {
   pushd $notes_dir
   files="$(find . -name "*$1*" | tr '\n' ' ')"
   echo files = $files
   if [ "$files" = "" ] ; then
      echo files empty, using grep
      files=$(grep --recursive --files-with-matches $1 . | tr '\n' ' ')
   fi
   $notes_editor $files
   popd
}


if [ $command = notes ] ; then
   openFile $1
else
   findFile $1
fi

