#!/bin/bash

command=$(basename $0)
notes_editor="ec -ct"
notes_prefix=Notes
notes_extension=org
if [ -z $PHIL_NOTES_DIR ] ; then
    notes_dir=$HOME/Dropbox/Notes/Notes_BUCKET
else
    notes_dir="$PHIL_NOTES_DIR"
fi

emacsclient -t -e '(notes)'

openFile()
{
    if [ "$1" != "" ] ; then
        file=${notes_prefix}_$1.org
    else
        file=${notes_prefix}_$(date +%m-%d).org
    fi
    eval $notes_editor $notes_dir/$file
}

findFile()
{
    files="$(find . -name "*$1*" | tr '\n' ' ')"

    echo files = $files
    if [ "$files" = "" ] ; then
        echo files empty, using grep
        files=$(grep --recursive --files-with-matches $1 . | tr '\n' ' ')
    fi

    eval $notes_editor $files
}
# Trying it out:
no_wait=--no-wait
for arg in $@ ; do
    if [ $arg = -t ] ; then
        no_wait=''
    fi
done

ec $notes_dir -c $no_wait $@

exit 0

if pushd $notes_dir > /dev/null 2>&1 ; then
    if [ $command = notes ] ; then
        openFile $1
    else
        findFile $1
    fi
    popd 
else
    echo "Could not cd into NOTES_DIR=$PHIL_NOTES_DIR"
    exit 1
fi

