#!/bin/bash

# This works with loop-tree.
# loop-tree continuously displays the contents (using tree) of the directory
# named in ~/.philpwd.

if ! builtin cd "$1" ; then
    return
fi

pwd > ~/.philpwd
